### ISSUE TITLE
Incorect coverage result

### ISSUE THREAD

**Issue by Tirex** [lshift/cloverage#76] opened 2015-06-06 18:23 UTC
Trying test this sample
https://github.com/Tirex/clojure1
And check coverage.
![cloverage](https://cloud.githubusercontent.com/assets/1099257/8020866/12c014f2-0cab-11e5-95a3-3e674741b836.png)
In the tests lines 10 and 11 are covered, but not counted and not highlighted.

Works correctly if change it in one line:
![scr3](https://cloud.githubusercontent.com/assets/1099257/8022424/6cbd956e-0cf2-11e5-84aa-edbe69c8fa40.png)

**Comment by palfrey** [comment] 2015-07-22 14:22
Now that #79 has been merged, this might be fixed.

**Comment by Tirex** [comment] 2015-07-24 07:43
Try current master, same thing.

**Comment by dlobue** [comment] 2015-07-26 00:02
So the reason why this is happening is because metadata containing line information isn't attached to base types like strings or numbers. The following would take advantage #79 for example:

    (if (= i 0)
        (str "0")
        (str "1"))

**Comment by rm-hull** [comment] 2016-08-11 08:45
Using the indexed pushback reader doesn't help here as the problem remains that metadata can't be added to literals. This is really a dupe of #12, and probably should be closed.

cc: @lvh

**Comment by lvh** [comment] 2016-08-11 23:37
Agreed; thanks @rm-hull :)

**Closed by lvh** 2016-08-11 23:37 UTC
