### ISSUE TITLE
'for' incorrect coverage

### ISSUE THREAD

**Issue by Tirex** [lshift/cloverage#86] opened 2015-10-29 13:12 UTC
Line in body of 'for' statement not counted in statistics and not highlited as not covered.
![for_coverage](https://cloud.githubusercontent.com/assets/1099257/10819157/c7c0cd9c-7e70-11e5-93ab-6a0a3b7dfe93.png)

test from this sample
https://github.com/Tirex/clojure1

**Comment by rm-hull** [comment] 2016-08-09 23:52
This is a duplicate of #23, and possibly fixed by #72.

@lvh can you close this issue?

**Comment by lvh** [comment] 2016-08-10 01:26
Closed as duplicate as @rm-hull mentioned.

**Closed by lvh** 2016-08-10 01:26 UTC
