### ISSUE TITLE
potemkin/defrecord+ results in cloverage RuntimeException

### ISSUE THREAD

**Issue by timclemons** [lshift/cloverage#47] opened 2014-05-07 18:56 UTC
Using `defrecord+` in the potemkin library, https://github.com/ztellman/potemkin, can result in an RuntimeException when running cloverage on the code.

The error appears to depend on having a `let` block inside one of the record's methods.  Here's a minimal repro:

````clojure
(ns 'foo.core
  (:use potemkin))

(defrecord+ CompareImpl [^long x]
  Comparable
  (compareTo [this o]
    (let [^long y o]
      (compare x y))))
````

Running `lein cloverage` results in the following exception:

````
Caused by: java.lang.RuntimeException: Unable to resolve symbol: o in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:6940)
	at clojure.lang.Compiler.resolve(Compiler.java:6884)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6845)
	at clojure.lang.Compiler.analyze(Compiler.java:6427)
	... 133 more
````

Removing the `let` or using regular `defrecord` both keep the exception from occurring.

**Comment by palfrey** [comment] 2015-07-30 16:35
Both riddley (to 0.1.10) and tools.cli (to 0.3.1) are now upgraded. Are you still seeing this problem?

**Comment by lvh** [comment] 2016-08-08 20:51
This has been open for a while, and it looks like the issue is resolved, so I'm closing this.

**Closed by lvh** 2016-08-08 20:51 UTC
Labels: bug
