### ISSUE TITLE
.cljc support

### ISSUE THREAD

**Issue by wiseman** [lshift/cloverage#97] opened 2016-05-04 20:38 UTC
It [looks like](https://github.com/lshift/cloverage/blob/38da3b05b6ebadfa1d84c24c1a8f1f9d2fb80fd5/cloverage/src/cloverage/source.clj#L7) cloverage doesn't work with `.cljc` files, is that correct?

I'm seeing an error when I run `lein cloverage` with 1.0.6. I have a file called `pid.cljc`, but not `pid.clj`.

```
[wiseman@John-Wisemans-MBP pid (master)]$ lein cloverage
Loading namespaces:  (com.lemondronor.pid)
Test namespaces:  (com.lemondronor.pid-test)
Exception in thread "main" java.lang.IllegalArgumentException: Cannot find resource com/lemondronor/pid.clj, compiling:(/private/var/folders/mz/chqj8b3s2lsdb49hjxt37czw0000gn/T/form-init4207805907360358075.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: Cannot find resource com/lemondronor/pid.clj
	at cloverage.source$resource_reader.invokeStatic(source.clj:20)
	at cloverage.source$resource_reader.invoke(source.clj:15)
	at cloverage.source$form_reader.invokeStatic(source.clj:23)
	at cloverage.source$form_reader.invoke(source.clj:22)
	at cloverage.source$ns_form.invokeStatic(source.clj:33)
	at cloverage.source$ns_form.invoke(source.clj:32)
	at cloverage.dependency$in_dependency_order$fn__2053.invoke(dependency.clj:69)
	at clojure.core$map$fn__4785.invoke(core.clj:2646)
...
```

**Comment by palfrey** [comment] 2016-05-05 09:21
Correct. Duplicate of #93

**Closed by palfrey** 2016-05-05 09:21 UTC
